[package]
name = "book-pictures"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
env_logger = "0.11.5"
image = "0.25.5"
log = "0.4.22"
num-complex = "0.4.6"
rand = "0.8.5"
regex = "1.11.1"
svg = "0.18.0"
